name: Send Email Manually
on:
  workflow_dispatch:
    inputs:
      recipient:
        type: input
        description: 'To'
        required: true
      subject:
        type: input
        description: 'Subject'
        required: true
      message:
        type: markdown
        description: 'Text'
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.event.inputs.subject }}
          body: ${{ github.event.inputs.message }}
          to: ${{ github.event.inputs.recipient }}
          from: Robot Matěje Štágla
          secure: true